exports.seed = function (knex) {
            return knex('books').insert([
                { title: 'Prealgebra', publisher: 'OpenStax', license: 'License v4.0', access_link: 'https://openstax.org/details/books/prealgebra', thumbnail: 'https://d3bxy9euw4e147.cloudfront.net/oscms-prodcms/media/documents/prealgebra_1.svg', description: 'Prealgebra is designed to meet scope and sequence requirements for a one-semester prealgebra course. The book’s organization makes it easy to adapt to a variety of course syllabi. The text introduces the fundamental concepts of algebra while addressing the needs of students with diverse backgrounds and learning styles. Each topic builds upon previously developed material to demonstrate the cohesiveness and structure of mathematics.', tag: 'Math'},
                { title: 'Precalculus', publisher: 'OpenStax', license: 'License v4.0', access_link: 'https://openstax.org/details/books/precalculus', thumbnail: 'https://d3bxy9euw4e147.cloudfront.net/oscms-prodcms/media/documents/precalculus.svg', description: 'Precalculus is adaptable and designed to fit the needs of a variety of precalculus courses. It is a comprehensive text that covers more ground than a typical one- or two-semester college-level precalculus course. The content is organized by clearly-defined learning objectives and includes worked examples that demonstrate problem-solving approaches in an accessible way.', tag: 'Math' },
                { title: 'Introductory Business Statistics', publisher: 'OpenStax', license: 'License v4.0', access_link: 'https://openstax.org/details/books/introductory-business-statistics', thumbnail: 'https://d3bxy9euw4e147.cloudfront.net/oscms-prodcms/media/documents/IntroductoryBusinessStatistics-bookcard.svg', description: 'Introductory Business Statistics is designed to meet the scope and sequence requirements of the one-semester statistics course for business, economics, and related majors. Core statistical concepts and skills have been augmented with practical business examples, scenarios, and exercises.', tag: 'Math' },
                { title: 'American Government', publisher: 'OpenStax', license: 'License v4.0', access_link: 'https://openstax.org/details/books/american-government-2e', thumbnail: 'https://d3bxy9euw4e147.cloudfront.net/oscms-prodcms/media/documents/american_government_2e_book_card.svg', description: 'American Government 2e is designed to meet the scope and sequence requirements of the single-semester American Government course. This title includes innovative features designed to enhance student learning, including Insider Perspective features and a Get Connected module that shows students how they can get engaged in the political process.', tag: 'Social Sciences' },
                { title: 'Principles of Economics', publisher: 'OpenStax', license: 'License v4.0', access_link: 'https://openstax.org/details/books/principles-economics-2e', thumbnail: 'https://d3bxy9euw4e147.cloudfront.net/oscms-prodcms/media/documents/Economics2e-BookCard.png', description: 'Principles of Economics 2e covers the scope and sequence of most introductory economics courses. The text includes many current examples, which are handled in a politically equitable way.', tag: 'Social Sciences' },
                { title: 'Principles of Macroeconomics', publisher: 'OpenStax', license: 'License v4.0', access_link: 'https://openstax.org/details/books/principles-macroeconomics-2e', thumbnail: 'https://d3bxy9euw4e147.cloudfront.net/oscms-prodcms/media/documents/Macroeconomics2e-BookCard.png', description: 'Principles of Macroeconomics 2e covers the scope and sequence of most introductory economics courses. The text includes many current examples, which are handled in a politically equitable way. The outcome is a balanced approach to the theory and application of economics concepts.', tag: 'Social Sciences' },
                { title: 'Introduction to Business', publisher: 'OpenStax', license: 'License v4.0', access_link: 'https://openstax.org/details/books/introduction-business', thumbnail: 'https://d3bxy9euw4e147.cloudfront.net/oscms-prodcms/media/documents/introduction_to_business.svg', description: 'Introduction to Business covers the scope and sequence of most introductory business courses. The book provides detailed explanations in the context of core themes such as customer satisfaction, ethics, entrepreneurship, global business, and managing change.', tag: 'Business' },
                { title: 'Entrepreneurship', publisher: 'OpenStax', license: 'License v4.0', access_link: 'https://openstax.org/details/books/entrepreneurship', thumbnail: 'https://d3bxy9euw4e147.cloudfront.net/oscms-prodcms/media/documents/entrepreneurship_book_card.svg', description: 'This textbook is intended for use in introductory Entrepreneurship classes at the undergraduate level. Due to the wide range of audiences and course approaches, the book is designed to be as flexible as possible.', tag: 'Business' },
                { title: 'Principles of Accounting', publisher: 'OpenStax', license: 'License v4.0', access_link: 'https://openstax.org/details/books/principles-financial-accounting', thumbnail: 'https://d3bxy9euw4e147.cloudfront.net/oscms-prodcms/media/documents/principles_of_acounting_volume_1_book_card.svg', description: 'Principles of Accounting is designed to meet the scope and sequence requirements of a two-semester accounting course that covers the fundamentals of financial and managerial accounting. Due to the comprehensive nature of the material, we are offering the book in two volumes.', tag: 'Business' },
            ])
}