exports.seed = function (knex) {
    // return knex('books').truncate()
    //     .then(function () {
            return knex('books').insert([
                { title: 'Prealgebra', publisher: 'OpenStax', license: 'License v4.0', access_link: 'https://openstax.org/details/books/prealgebra', thumbnail: 'https://d3bxy9euw4e147.cloudfront.net/oscms-prodcms/media/documents/prealgebra_1.svg', description: 'Prealgebra is designed to meet scope and sequence requirements for a one-semester prealgebra course. The book’s organization makes it easy to adapt to a variety of course syllabi. The text introduces the fundamental concepts of algebra while addressing the needs of students with diverse backgrounds and learning styles. Each topic builds upon previously developed material to demonstrate the cohesiveness and structure of mathematics.', tag: 'Math'},
                { title: 'Precalculus', publisher: 'OpenStax', license: 'License v4.0', access_link: 'https://openstax.org/details/books/precalculus', thumbnail: 'https://d3bxy9euw4e147.cloudfront.net/oscms-prodcms/media/documents/precalculus.svg', description: 'Precalculus is adaptable and designed to fit the needs of a variety of precalculus courses. It is a comprehensive text that covers more ground than a typical one- or two-semester college-level precalculus course. The content is organized by clearly-defined learning objectives and includes worked examples that demonstrate problem-solving approaches in an accessible way.', tag: 'Math' },
                { title: 'Statistics', publisher: 'OpenStax', license: 'License v4.0', access_link: 'https://openstax.org/details/books/introductory-business-statistics', thumbnail: 'https://d3bxy9euw4e147.cloudfront.net/oscms-prodcms/media/documents/IntroductoryBusinessStatistics-bookcard.svg', description: 'Introductory Business Statistics is designed to meet the scope and sequence requirements of the one-semester statistics course for business, economics, and related majors. Core statistical concepts and skills have been augmented with practical business examples, scenarios, and exercises.', tag: 'Math' },
            ])
        // })
}